version: '3.7'
services:
  db:
    image: colemanword/userdb:latest
    env_file:
      - userdb.env
    ports:
      - "8080:8080"
    volumes:
      - default:/tmp/userdb
    networks:
      default:
        aliases:
          - userdb
networks:
  default:

volumes:
  default:
